### ISSUE TITLE
Feature - Combined view and editing watchlists

### ISSUE THREAD

**Issue by Martenere** [Watchlist-project/movie-watchlist-frontend#36]
A user should be able to watch one watchlist, decided through the url, and and select another to edit.

The currently viewed watchlist should be marked as green in the navigation view, the currently "edited" watchlist should be marked with the pen checkbox icon

**Comment by LinusWillmont** [comment]
To save time this is not implemented and instead when clicking on a watchlist the edit index is also moved to the same watchlist
