### ISSUE TITLE
Create the "search for movies" page

### ISSUE THREAD

**Issue by Martenere** [Watchlist-project/movie-watchlist-frontend#6]
Need to implement,
Searchbar
MovieCardList
Moviecard component
fetch call from api TMDB

Closing criteria: 
Can input search string and get a view of movies fetched from tmdb

*ignore left side navigation view*
![Image](https://github.com/Watchlist-project/movie-watchlist-backend/assets/78728730/f9dce26c-b46b-4822-ab4a-420b57215777)

**Comment by dogezen** [comment]
Missing: details of the interactions each component should handle, with the action that results from that interaction
Ie. what should happen when I type in the searchbar? do I have to click search, or it searches on each keystroke? does it make a fetch request for each new search, or does it work with local data only, etc... all of these decisions should be captured and documented for the search component...
